"""create_curriculum_tables

Revision ID: 4394dfc92b94
Revises: 9f7d521734f6
Create Date: 2026-08-02 22:13:50.174574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4394dfc92b94'
down_revision: Union[str, Sequence[str], None] = '9f7d521734f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_paths',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_role', sa.String(length=50), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_paths_slug'), 'learning_paths', ['slug'], unique=True)
    op.create_table('curriculum_modules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('path_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_unlocked_by_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['path_id'], ['learning_paths.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curriculum_modules_path_id'), 'curriculum_modules', ['path_id'], unique=False)
    op.create_index(op.f('ix_curriculum_modules_slug'), 'curriculum_modules', ['slug'], unique=True)
    op.create_table('student_learning_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('current_path_id', sa.UUID(), nullable=True),
    sa.Column('current_module_id', sa.UUID(), nullable=True),
    sa.Column('unlocked_module_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('unlocked_lesson_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('completed_lesson_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('skill_levels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('weak_areas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('practice_streak_days', sa.Integer(), nullable=True),
    sa.Column('total_xp', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_learning_states_user_id'), 'student_learning_states', ['user_id'], unique=True)
    op.create_table('curriculum_checkpoints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('pass_threshold_percentage', sa.Float(), nullable=True),
    sa.Column('unlocks_module_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['curriculum_modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curriculum_checkpoints_module_id'), 'curriculum_checkpoints', ['module_id'], unique=False)
    op.create_table('curriculum_units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['curriculum_modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curriculum_units_module_id'), 'curriculum_units', ['module_id'], unique=False)
    op.create_index(op.f('ix_curriculum_units_slug'), 'curriculum_units', ['slug'], unique=False)
    op.create_table('curriculum_lessons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('learning_goal', sa.Text(), nullable=True),
    sa.Column('estimated_time', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('required_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('skills_taught', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prerequisites', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('xp_reward', sa.Integer(), nullable=True),
    sa.Column('ai_coaching_enabled', sa.Boolean(), nullable=True),
    sa.Column('teacher_assignable', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['curriculum_units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curriculum_lessons_slug'), 'curriculum_lessons', ['slug'], unique=True)
    op.create_index(op.f('ix_curriculum_lessons_unit_id'), 'curriculum_lessons', ['unit_id'], unique=False)
    op.create_table('curriculum_exercises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('exercise_type', sa.String(length=50), nullable=True),
    sa.Column('tempo_bpm', sa.Integer(), nullable=True),
    sa.Column('key_signature', sa.String(length=20), nullable=True),
    sa.Column('midi_uri', sa.String(length=1024), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['curriculum_lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curriculum_exercises_lesson_id'), 'curriculum_exercises', ['lesson_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_curriculum_exercises_lesson_id'), table_name='curriculum_exercises')
    op.drop_table('curriculum_exercises')
    op.drop_index(op.f('ix_curriculum_lessons_unit_id'), table_name='curriculum_lessons')
    op.drop_index(op.f('ix_curriculum_lessons_slug'), table_name='curriculum_lessons')
    op.drop_table('curriculum_lessons')
    op.drop_index(op.f('ix_curriculum_units_slug'), table_name='curriculum_units')
    op.drop_index(op.f('ix_curriculum_units_module_id'), table_name='curriculum_units')
    op.drop_table('curriculum_units')
    op.drop_index(op.f('ix_curriculum_checkpoints_module_id'), table_name='curriculum_checkpoints')
    op.drop_table('curriculum_checkpoints')
    op.drop_index(op.f('ix_student_learning_states_user_id'), table_name='student_learning_states')
    op.drop_table('student_learning_states')
    op.drop_index(op.f('ix_curriculum_modules_slug'), table_name='curriculum_modules')
    op.drop_index(op.f('ix_curriculum_modules_path_id'), table_name='curriculum_modules')
    op.drop_table('curriculum_modules')
    op.drop_index(op.f('ix_learning_paths_slug'), table_name='learning_paths')
    op.drop_table('learning_paths')
    # ### end Alembic commands ###
