"""add_pipeline_models

Revision ID: 62f879a6c3de
Revises: d3c7fb8db6f9
Create Date: 2026-08-16 22:56:46.622570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision: str = '62f879a6c3de'
down_revision: Union[str, Sequence[str], None] = 'd3c7fb8db6f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_learning_states', sa.Column('performance_history', app.models.json_type.ConditionalJSON(), nullable=True))
    op.add_column('student_learning_states', sa.Column('current_difficulty', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_learning_states', 'current_difficulty')
    op.drop_column('student_learning_states', 'performance_history')
    # ### end Alembic commands ###
