"""enhance_lesson_and_add_lesson_progress

Revision ID: 74dde4aede2b
Revises: 94547ee417ae
Create Date: 2026-07-26 20:46:06.091646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '74dde4aede2b'
down_revision: Union[str, Sequence[str], None] = '94547ee417ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('progress_percentage', sa.Float(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('last_opened', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_progress_lesson_id'), 'lesson_progress', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_lesson_progress_user_id'), 'lesson_progress', ['user_id'], unique=False)
    op.add_column('lessons', sa.Column('slug', sa.String(length=300), nullable=True))
    # Populate existing rows with a default slug based on ID
    op.execute("UPDATE lessons SET slug = 'lesson-' || CAST(id AS VARCHAR) WHERE slug IS NULL")
    op.alter_column('lessons', 'slug', nullable=False)
    op.add_column('lessons', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('lessons', sa.Column('display_order', sa.Integer(), nullable=True))
    op.add_column('lessons', sa.Column('objectives', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('lessons', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('lessons', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('lessons', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_lessons_category'), 'lessons', ['category'], unique=False)
    op.create_index(op.f('ix_lessons_difficulty'), 'lessons', ['difficulty'], unique=False)
    op.create_index(op.f('ix_lessons_is_deleted'), 'lessons', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_lessons_is_published'), 'lessons', ['is_published'], unique=False)
    op.create_index(op.f('ix_lessons_slug'), 'lessons', ['slug'], unique=True)
    op.create_index(op.f('ix_lessons_teacher_id'), 'lessons', ['teacher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lessons_teacher_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_slug'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_is_published'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_is_deleted'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_difficulty'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_category'), table_name='lessons')
    op.drop_column('lessons', 'deleted_at')
    op.drop_column('lessons', 'is_deleted')
    op.drop_column('lessons', 'published_at')
    op.drop_column('lessons', 'objectives')
    op.drop_column('lessons', 'display_order')
    op.drop_column('lessons', 'category')
    op.drop_column('lessons', 'slug')
    op.drop_index(op.f('ix_lesson_progress_user_id'), table_name='lesson_progress')
    op.drop_index(op.f('ix_lesson_progress_lesson_id'), table_name='lesson_progress')
    op.drop_table('lesson_progress')
    # ### end Alembic commands ###
