import app
import app.models.json_type
"""Initial schema

Revision ID: c1e927bbdbcb
Revises: 
Create Date: 2026-08-07 14:51:21.326002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1e927bbdbcb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_paths',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_role', sa.String(length=50), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_paths_slug'), 'learning_paths', ['slug'], unique=True)
    op.create_table('curriculum_modules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('path_id', app.models.json_type.ConditionalUUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_unlocked_by_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['path_id'], ['learning_paths.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curriculum_modules_path_id'), 'curriculum_modules', ['path_id'], unique=False)
    op.create_index(op.f('ix_curriculum_modules_slug'), 'curriculum_modules', ['slug'], unique=True)
    op.create_table('friend_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('receiver_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sender_id', 'receiver_id', name='uq_friend_request_sender_receiver')
    )
    op.create_index(op.f('ix_friend_requests_receiver_id'), 'friend_requests', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_friend_requests_sender_id'), 'friend_requests', ['sender_id'], unique=False)
    op.create_table('friendships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('friend_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'friend_id', name='uq_friendship_user_friend')
    )
    op.create_index(op.f('ix_friendships_friend_id'), 'friendships', ['friend_id'], unique=False)
    op.create_index(op.f('ix_friendships_user_id'), 'friendships', ['user_id'], unique=False)
    op.create_table('profiles',
    sa.Column('id', app.models.json_type.ConditionalUUID(), nullable=False),
    sa.Column('user_id', app.models.json_type.ConditionalUUID(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('skill_level', sa.String(length=50), nullable=True),
    sa.Column('preferred_instrument', sa.String(length=100), nullable=True),
    sa.Column('daily_practice_goal', sa.Integer(), nullable=True),
    sa.Column('preferred_genres', app.models.json_type.ConditionalJSON(), nullable=True),
    sa.Column('learning_preferences', app.models.json_type.ConditionalJSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('student_learning_states',
    sa.Column('id', app.models.json_type.ConditionalUUID(), nullable=False),
    sa.Column('user_id', app.models.json_type.ConditionalUUID(), nullable=False),
    sa.Column('current_path_id', app.models.json_type.ConditionalUUID(), nullable=True),
    sa.Column('current_module_id', app.models.json_type.ConditionalUUID(), nullable=True),
    sa.Column('unlocked_module_ids', app.models.json_type.ConditionalJSON(), nullable=True),
    sa.Column('unlocked_lesson_ids', app.models.json_type.ConditionalJSON(), nullable=True),
    sa.Column('completed_lesson_ids', app.models.json_type.ConditionalJSON(), nullable=True),
    sa.Column('skill_levels', app.models.json_type.ConditionalJSON(), nullable=True),
    sa.Column('weak_areas', app.models.json_type.ConditionalJSON(), nullable=True),
    sa.Column('ai_recommendations', app.models.json_type.ConditionalJSON(), nullable=True),
    sa.Column('practice_streak_days', sa.Integer(), nullable=True),
    sa.Column('total_xp', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_learning_states_user_id'), 'student_learning_states', ['user_id'], unique=True)
    op.create_table('curriculum_checkpoints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('pass_threshold_percentage', sa.Float(), nullable=True),
    sa.Column('unlocks_module_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['curriculum_modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curriculum_checkpoints_module_id'), 'curriculum_checkpoints', ['module_id'], unique=False)
    op.create_table('curriculum_units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['curriculum_modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curriculum_units_module_id'), 'curriculum_units', ['module_id'], unique=False)
    op.create_index(op.f('ix_curriculum_units_slug'), 'curriculum_units', ['slug'], unique=False)
    op.create_table('lesson_progress',
    sa.Column('id', app.models.json_type.ConditionalUUID(), nullable=False),
    sa.Column('user_id', app.models.json_type.ConditionalUUID(), nullable=False),
    sa.Column('lesson_id', app.models.json_type.ConditionalUUID(), nullable=False),
    sa.Column('progress_percentage', sa.Float(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('last_opened', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_progress_lesson_id'), 'lesson_progress', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_lesson_progress_user_id'), 'lesson_progress', ['user_id'], unique=False)
    op.create_table('lesson_song',
    sa.Column('lesson_id', app.models.json_type.ConditionalUUID(), nullable=False),
    sa.Column('song_id', app.models.json_type.ConditionalUUID(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lesson_id', 'song_id')
    )
    op.create_table('curriculum_lessons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('learning_goal', sa.Text(), nullable=True),
    sa.Column('estimated_time', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('required_skills', app.models.json_type.ConditionalJSON(), nullable=True),
    sa.Column('skills_taught', app.models.json_type.ConditionalJSON(), nullable=True),
    sa.Column('objective', app.models.json_type.ConditionalJSON(), nullable=True),
    sa.Column('prerequisites', app.models.json_type.ConditionalJSON(), nullable=True),
    sa.Column('xp_reward', sa.Integer(), nullable=True),
    sa.Column('ai_coaching_enabled', sa.Boolean(), nullable=True),
    sa.Column('teacher_assignable', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['curriculum_units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curriculum_lessons_slug'), 'curriculum_lessons', ['slug'], unique=True)
    op.create_index(op.f('ix_curriculum_lessons_unit_id'), 'curriculum_lessons', ['unit_id'], unique=False)
    op.create_table('curriculum_exercises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('exercise_type', sa.String(length=50), nullable=True),
    sa.Column('tempo_bpm', sa.Integer(), nullable=True),
    sa.Column('key_signature', sa.String(length=20), nullable=True),
    sa.Column('midi_uri', sa.String(length=1024), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['curriculum_lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curriculum_exercises_lesson_id'), 'curriculum_exercises', ['lesson_id'], unique=False)
    op.add_column('lessons', sa.Column('slug', sa.String(length=300), nullable=False))
    op.add_column('lessons', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('lessons', sa.Column('display_order', sa.Integer(), nullable=True))
    op.add_column('lessons', sa.Column('objectives', app.models.json_type.ConditionalJSON(), nullable=True))
    op.add_column('lessons', sa.Column('sections', app.models.json_type.ConditionalJSON(), nullable=True))
    op.add_column('lessons', sa.Column('steps', app.models.json_type.ConditionalJSON(), nullable=True))
    op.add_column('lessons', sa.Column('adaptive_thresholds', app.models.json_type.ConditionalJSON(), nullable=True))
    op.add_column('lessons', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('lessons', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('lessons', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('lessons', 'id',
               existing_type=sa.NUMERIC(),
               type_=app.models.json_type.ConditionalUUID(),
               existing_nullable=False)
    op.alter_column('lessons', 'teacher_id',
               existing_type=sa.NUMERIC(),
               type_=app.models.json_type.ConditionalUUID(),
               existing_nullable=True)
    op.create_index(op.f('ix_lessons_category'), 'lessons', ['category'], unique=False)
    op.create_index(op.f('ix_lessons_difficulty'), 'lessons', ['difficulty'], unique=False)
    op.create_index(op.f('ix_lessons_is_deleted'), 'lessons', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_lessons_is_published'), 'lessons', ['is_published'], unique=False)
    op.create_index(op.f('ix_lessons_slug'), 'lessons', ['slug'], unique=True)
    op.create_index(op.f('ix_lessons_teacher_id'), 'lessons', ['teacher_id'], unique=False)
    op.add_column('songs', sa.Column('educational_category', sa.String(length=100), nullable=True))
    op.add_column('songs', sa.Column('learning_objectives', app.models.json_type.ConditionalJSON(), nullable=True))
    op.add_column('songs', sa.Column('skills_required', app.models.json_type.ConditionalJSON(), nullable=True))
    op.add_column('songs', sa.Column('skills_reinforced', app.models.json_type.ConditionalJSON(), nullable=True))
    op.add_column('songs', sa.Column('prerequisite_lesson_slugs', app.models.json_type.ConditionalJSON(), nullable=True))
    op.add_column('songs', sa.Column('mastery_threshold_percentage', sa.Float(), nullable=True))
    op.add_column('songs', sa.Column('missions', app.models.json_type.ConditionalJSON(), nullable=True))
    op.add_column('songs', sa.Column('sections', app.models.json_type.ConditionalJSON(), nullable=True))
    op.add_column('songs', sa.Column('steps', app.models.json_type.ConditionalJSON(), nullable=True))
    op.add_column('songs', sa.Column('adaptive_thresholds', app.models.json_type.ConditionalJSON(), nullable=True))
    op.add_column('songs', sa.Column('ai_coaching_focus', app.models.json_type.ConditionalJSON(), nullable=True))
    op.add_column('songs', sa.Column('teacher_notes', sa.Text(), nullable=True))
    op.alter_column('songs', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.create_index(op.f('ix_songs_created_at'), 'songs', ['created_at'], unique=False)
    op.create_index(op.f('ix_songs_difficulty'), 'songs', ['difficulty'], unique=False)
    op.create_index(op.f('ix_songs_educational_category'), 'songs', ['educational_category'], unique=False)
    op.create_index(op.f('ix_songs_title'), 'songs', ['title'], unique=False)
    op.alter_column('users', 'id',
               existing_type=sa.NUMERIC(),
               type_=app.models.json_type.ConditionalUUID(),
               existing_nullable=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=1)
    op.alter_column('users', 'id',
               existing_type=app.models.json_type.ConditionalUUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_index(op.f('ix_songs_title'), table_name='songs')
    op.drop_index(op.f('ix_songs_educational_category'), table_name='songs')
    op.drop_index(op.f('ix_songs_difficulty'), table_name='songs')
    op.drop_index(op.f('ix_songs_created_at'), table_name='songs')
    op.alter_column('songs', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('songs', 'teacher_notes')
    op.drop_column('songs', 'ai_coaching_focus')
    op.drop_column('songs', 'adaptive_thresholds')
    op.drop_column('songs', 'steps')
    op.drop_column('songs', 'sections')
    op.drop_column('songs', 'missions')
    op.drop_column('songs', 'mastery_threshold_percentage')
    op.drop_column('songs', 'prerequisite_lesson_slugs')
    op.drop_column('songs', 'skills_reinforced')
    op.drop_column('songs', 'skills_required')
    op.drop_column('songs', 'learning_objectives')
    op.drop_column('songs', 'educational_category')
    op.drop_index(op.f('ix_lessons_teacher_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_slug'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_is_published'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_is_deleted'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_difficulty'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_category'), table_name='lessons')
    op.alter_column('lessons', 'teacher_id',
               existing_type=app.models.json_type.ConditionalUUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('lessons', 'id',
               existing_type=app.models.json_type.ConditionalUUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('lessons', 'deleted_at')
    op.drop_column('lessons', 'is_deleted')
    op.drop_column('lessons', 'published_at')
    op.drop_column('lessons', 'adaptive_thresholds')
    op.drop_column('lessons', 'steps')
    op.drop_column('lessons', 'sections')
    op.drop_column('lessons', 'objectives')
    op.drop_column('lessons', 'display_order')
    op.drop_column('lessons', 'category')
    op.drop_column('lessons', 'slug')
    op.drop_index(op.f('ix_curriculum_exercises_lesson_id'), table_name='curriculum_exercises')
    op.drop_table('curriculum_exercises')
    op.drop_index(op.f('ix_curriculum_lessons_unit_id'), table_name='curriculum_lessons')
    op.drop_index(op.f('ix_curriculum_lessons_slug'), table_name='curriculum_lessons')
    op.drop_table('curriculum_lessons')
    op.drop_table('lesson_song')
    op.drop_index(op.f('ix_lesson_progress_user_id'), table_name='lesson_progress')
    op.drop_index(op.f('ix_lesson_progress_lesson_id'), table_name='lesson_progress')
    op.drop_table('lesson_progress')
    op.drop_index(op.f('ix_curriculum_units_slug'), table_name='curriculum_units')
    op.drop_index(op.f('ix_curriculum_units_module_id'), table_name='curriculum_units')
    op.drop_table('curriculum_units')
    op.drop_index(op.f('ix_curriculum_checkpoints_module_id'), table_name='curriculum_checkpoints')
    op.drop_table('curriculum_checkpoints')
    op.drop_index(op.f('ix_student_learning_states_user_id'), table_name='student_learning_states')
    op.drop_table('student_learning_states')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_friendships_user_id'), table_name='friendships')
    op.drop_index(op.f('ix_friendships_friend_id'), table_name='friendships')
    op.drop_table('friendships')
    op.drop_index(op.f('ix_friend_requests_sender_id'), table_name='friend_requests')
    op.drop_index(op.f('ix_friend_requests_receiver_id'), table_name='friend_requests')
    op.drop_table('friend_requests')
    op.drop_index(op.f('ix_curriculum_modules_slug'), table_name='curriculum_modules')
    op.drop_index(op.f('ix_curriculum_modules_path_id'), table_name='curriculum_modules')
    op.drop_table('curriculum_modules')
    op.drop_index(op.f('ix_learning_paths_slug'), table_name='learning_paths')
    op.drop_table('learning_paths')
    # ### end Alembic commands ###
