"""Initial schema with real data pipeline models

Revision ID: d3c7fb8db6f9
Revises: 
Create Date: 2026-08-17 03:30:22.813557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision: str = 'd3c7fb8db6f9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_paths',
    sa.Column('id', app.models.json_type.ConditionalUUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_role', sa.String(length=50), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_paths_slug'), 'learning_paths', ['slug'], unique=True)
    op.create_table('songs',
    sa.Column('id', app.models.json_type.ConditionalUUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('composer', sa.String(length=255), nullable=True),
    sa.Column('artist', sa.String(length=255), nullable=True),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('bpm', sa.Integer(), nullable=True),
    sa.Column('key_signature', sa.String(length=20), nullable=True),
    sa.Column('time_signature', sa.String(length=20), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('file_url', sa.String(length=1024), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=1024), nullable=True),
    sa.Column('educational_category', sa.String(length=100), nullable=True),
    sa.Column('learning_objectives', app.models.json_type.ConditionalJSON(), nullable=True),
    sa.Column('skills_required', app.models.json_type.ConditionalJSON(), nullable=True),
    sa.Column('skills_reinforced', app.models.json_type.ConditionalJSON(), nullable=True),
    sa.Column('prerequisite_lesson_slugs', app.models.json_type.ConditionalJSON(), nullable=True),
    sa.Column('mastery_threshold_percentage', sa.Float(), nullable=True),
    sa.Column('missions', app.models.json_type.ConditionalJSON(), nullable=True),
    sa.Column('sections', app.models.json_type.ConditionalJSON(), nullable=True),
    sa.Column('steps', app.models.json_type.ConditionalJSON(), nullable=True),
    sa.Column('adaptive_thresholds', app.models.json_type.ConditionalJSON(), nullable=True),
    sa.Column('ai_coaching_focus', app.models.json_type.ConditionalJSON(), nullable=True),
    sa.Column('teacher_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_songs_created_at'), 'songs', ['created_at'], unique=False)
    op.create_index(op.f('ix_songs_difficulty'), 'songs', ['difficulty'], unique=False)
    op.create_index(op.f('ix_songs_educational_category'), 'songs', ['educational_category'], unique=False)
    op.create_index(op.f('ix_songs_title'), 'songs', ['title'], unique=False)
    op.create_table('users',
    sa.Column('id', app.models.json_type.ConditionalUUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('auth_provider', sa.String(length=50), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audio_assets',
    sa.Column('id', app.models.json_type.ConditionalUUID(), nullable=False),
    sa.Column('user_id', app.models.json_type.ConditionalUUID(), nullable=False),
    sa.Column('song_id', app.models.json_type.ConditionalUUID(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('file_hash_sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('channels', sa.Integer(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('validation_errors', app.models.json_type.ConditionalJSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash_sha256')
    )
    op.create_table('curriculum_modules',
    sa.Column('id', app.models.json_type.ConditionalUUID(), nullable=False),
    sa.Column('path_id', app.models.json_type.ConditionalUUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_unlocked_by_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['path_id'], ['learning_paths.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curriculum_modules_path_id'), 'curriculum_modules', ['path_id'], unique=False)
    op.create_index(op.f('ix_curriculum_modules_slug'), 'curriculum_modules', ['slug'], unique=True)
    op.create_table('friend_requests',
    sa.Column('id', app.models.json_type.ConditionalUUID(), nullable=False),
    sa.Column('sender_id', app.models.json_type.ConditionalUUID(), nullable=False),
    sa.Column('receiver_id', app.models.json_type.ConditionalUUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sender_id', 'receiver_id', name='uq_friend_request_sender_receiver')
    )
    op.create_index(op.f('ix_friend_requests_receiver_id'), 'friend_requests', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_friend_requests_sender_id'), 'friend_requests', ['sender_id'], unique=False)
    op.create_table('friendships',
    sa.Column('id', app.models.json_type.ConditionalUUID(), nullable=False),
    sa.Column('user_id', app.models.json_type.ConditionalUUID(), nullable=False),
    sa.Column('friend_id', app.models.json_type.ConditionalUUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'friend_id', name='uq_friendship_user_friend')
    )
    op.create_index(op.f('ix_friendships_friend_id'), 'friendships', ['friend_id'], unique=False)
    op.create_index(op.f('ix_friendships_user_id'), 'friendships', ['user_id'], unique=False)
    op.create_table('lessons',
    sa.Column('id', app.models.json_type.ConditionalUUID(), nullable=False),
    sa.Column('teacher_id', app.models.json_type.ConditionalUUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('estimated_duration', sa.Integer(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=1024), nullable=True),
    sa.Column('objectives', app.models.json_type.ConditionalJSON(), nullable=True),
    sa.Column('sections', app.models.json_type.ConditionalJSON(), nullable=True),
    sa.Column('steps', app.models.json_type.ConditionalJSON(), nullable=True),
    sa.Column('adaptive_thresholds', app.models.json_type.ConditionalJSON(), nullable=True),
    sa.Column('visibility', sa.String(length=50), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_category'), 'lessons', ['category'], unique=False)
    op.create_index(op.f('ix_lessons_difficulty'), 'lessons', ['difficulty'], unique=False)
    op.create_index(op.f('ix_lessons_is_deleted'), 'lessons', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_lessons_is_published'), 'lessons', ['is_published'], unique=False)
    op.create_index(op.f('ix_lessons_slug'), 'lessons', ['slug'], unique=True)
    op.create_index(op.f('ix_lessons_teacher_id'), 'lessons', ['teacher_id'], unique=False)
    op.create_table('profiles',
    sa.Column('id', app.models.json_type.ConditionalUUID(), nullable=False),
    sa.Column('user_id', app.models.json_type.ConditionalUUID(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('skill_level', sa.String(length=50), nullable=True),
    sa.Column('preferred_instrument', sa.String(length=100), nullable=True),
    sa.Column('daily_practice_goal', sa.Integer(), nullable=True),
    sa.Column('preferred_genres', app.models.json_type.ConditionalJSON(), nullable=True),
    sa.Column('learning_preferences', app.models.json_type.ConditionalJSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('student_learning_states',
    sa.Column('id', app.models.json_type.ConditionalUUID(), nullable=False),
    sa.Column('user_id', app.models.json_type.ConditionalUUID(), nullable=False),
    sa.Column('current_path_id', app.models.json_type.ConditionalUUID(), nullable=True),
    sa.Column('current_module_id', app.models.json_type.ConditionalUUID(), nullable=True),
    sa.Column('unlocked_module_ids', app.models.json_type.ConditionalJSON(), nullable=True),
    sa.Column('unlocked_lesson_ids', app.models.json_type.ConditionalJSON(), nullable=True),
    sa.Column('completed_lesson_ids', app.models.json_type.ConditionalJSON(), nullable=True),
    sa.Column('skill_levels', app.models.json_type.ConditionalJSON(), nullable=True),
    sa.Column('weak_areas', app.models.json_type.ConditionalJSON(), nullable=True),
    sa.Column('ai_recommendations', app.models.json_type.ConditionalJSON(), nullable=True),
    sa.Column('practice_streak_days', sa.Integer(), nullable=True),
    sa.Column('total_xp', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_learning_states_user_id'), 'student_learning_states', ['user_id'], unique=True)
    op.create_table('curriculum_checkpoints',
    sa.Column('id', app.models.json_type.ConditionalUUID(), nullable=False),
    sa.Column('module_id', app.models.json_type.ConditionalUUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('pass_threshold_percentage', sa.Float(), nullable=True),
    sa.Column('unlocks_module_id', app.models.json_type.ConditionalUUID(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['curriculum_modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curriculum_checkpoints_module_id'), 'curriculum_checkpoints', ['module_id'], unique=False)
    op.create_table('curriculum_units',
    sa.Column('id', app.models.json_type.ConditionalUUID(), nullable=False),
    sa.Column('module_id', app.models.json_type.ConditionalUUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['curriculum_modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curriculum_units_module_id'), 'curriculum_units', ['module_id'], unique=False)
    op.create_index(op.f('ix_curriculum_units_slug'), 'curriculum_units', ['slug'], unique=False)
    op.create_table('lesson_progress',
    sa.Column('id', app.models.json_type.ConditionalUUID(), nullable=False),
    sa.Column('user_id', app.models.json_type.ConditionalUUID(), nullable=False),
    sa.Column('lesson_id', app.models.json_type.ConditionalUUID(), nullable=False),
    sa.Column('progress_percentage', sa.Float(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('last_opened', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_progress_lesson_id'), 'lesson_progress', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_lesson_progress_user_id'), 'lesson_progress', ['user_id'], unique=False)
    op.create_table('lesson_song',
    sa.Column('lesson_id', app.models.json_type.ConditionalUUID(), nullable=False),
    sa.Column('song_id', app.models.json_type.ConditionalUUID(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lesson_id', 'song_id')
    )
    op.create_table('processing_jobs',
    sa.Column('id', app.models.json_type.ConditionalUUID(), nullable=False),
    sa.Column('audio_asset_id', app.models.json_type.ConditionalUUID(), nullable=False),
    sa.Column('song_id', app.models.json_type.ConditionalUUID(), nullable=True),
    sa.Column('user_id', app.models.json_type.ConditionalUUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('progress_percent', sa.Integer(), nullable=True),
    sa.Column('pipeline_version', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('stage_log', app.models.json_type.ConditionalJSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['audio_asset_id'], ['audio_assets.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curriculum_lessons',
    sa.Column('id', app.models.json_type.ConditionalUUID(), nullable=False),
    sa.Column('unit_id', app.models.json_type.ConditionalUUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('learning_goal', sa.Text(), nullable=True),
    sa.Column('estimated_time', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('required_skills', app.models.json_type.ConditionalJSON(), nullable=True),
    sa.Column('skills_taught', app.models.json_type.ConditionalJSON(), nullable=True),
    sa.Column('objective', app.models.json_type.ConditionalJSON(), nullable=True),
    sa.Column('prerequisites', app.models.json_type.ConditionalJSON(), nullable=True),
    sa.Column('xp_reward', sa.Integer(), nullable=True),
    sa.Column('ai_coaching_enabled', sa.Boolean(), nullable=True),
    sa.Column('teacher_assignable', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['curriculum_units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curriculum_lessons_slug'), 'curriculum_lessons', ['slug'], unique=True)
    op.create_index(op.f('ix_curriculum_lessons_unit_id'), 'curriculum_lessons', ['unit_id'], unique=False)
    op.create_table('transcriptions',
    sa.Column('id', app.models.json_type.ConditionalUUID(), nullable=False),
    sa.Column('processing_job_id', app.models.json_type.ConditionalUUID(), nullable=False),
    sa.Column('audio_asset_id', app.models.json_type.ConditionalUUID(), nullable=False),
    sa.Column('song_id', app.models.json_type.ConditionalUUID(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('raw_midi_path', sa.String(length=1024), nullable=True),
    sa.Column('model_output_path', sa.String(length=1024), nullable=True),
    sa.Column('note_events_path', sa.String(length=1024), nullable=True),
    sa.Column('note_count', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['audio_asset_id'], ['audio_assets.id'], ),
    sa.ForeignKeyConstraint(['processing_job_id'], ['processing_jobs.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('processing_job_id')
    )
    op.create_table('curriculum_exercises',
    sa.Column('id', app.models.json_type.ConditionalUUID(), nullable=False),
    sa.Column('lesson_id', app.models.json_type.ConditionalUUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('exercise_type', sa.String(length=50), nullable=True),
    sa.Column('tempo_bpm', sa.Integer(), nullable=True),
    sa.Column('key_signature', sa.String(length=20), nullable=True),
    sa.Column('midi_uri', sa.String(length=1024), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['curriculum_lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curriculum_exercises_lesson_id'), 'curriculum_exercises', ['lesson_id'], unique=False)
    op.create_table('difficulty_variants',
    sa.Column('id', app.models.json_type.ConditionalUUID(), nullable=False),
    sa.Column('transcription_id', app.models.json_type.ConditionalUUID(), nullable=False),
    sa.Column('song_id', app.models.json_type.ConditionalUUID(), nullable=True),
    sa.Column('processing_job_id', app.models.json_type.ConditionalUUID(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('metrics', app.models.json_type.ConditionalJSON(), nullable=True),
    sa.Column('difficulty_score', sa.Float(), nullable=True),
    sa.Column('note_count', sa.Integer(), nullable=True),
    sa.Column('tempo_multiplier', sa.Float(), nullable=True),
    sa.Column('hands_used', sa.String(length=20), nullable=True),
    sa.Column('engine_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['processing_job_id'], ['processing_jobs.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.ForeignKeyConstraint(['transcription_id'], ['transcriptions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transcription_id', 'level', name='uq_transcription_level')
    )
    op.create_table('processing_provenances',
    sa.Column('id', app.models.json_type.ConditionalUUID(), nullable=False),
    sa.Column('processing_job_id', app.models.json_type.ConditionalUUID(), nullable=False),
    sa.Column('song_id', app.models.json_type.ConditionalUUID(), nullable=True),
    sa.Column('audio_asset_id', app.models.json_type.ConditionalUUID(), nullable=False),
    sa.Column('transcription_id', app.models.json_type.ConditionalUUID(), nullable=True),
    sa.Column('pipeline_version', sa.String(length=20), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('audio_duration', sa.Float(), nullable=True),
    sa.Column('transcription_model', sa.String(length=100), nullable=True),
    sa.Column('transcription_model_version', sa.String(length=50), nullable=True),
    sa.Column('bpm_engine_version', sa.String(length=20), nullable=True),
    sa.Column('difficulty_engine_version', sa.String(length=20), nullable=True),
    sa.Column('tempo_value', sa.Float(), nullable=True),
    sa.Column('tempo_confidence', sa.Float(), nullable=True),
    sa.Column('note_count', sa.Integer(), nullable=True),
    sa.Column('difficulty_variants_summary', app.models.json_type.ConditionalJSON(), nullable=True),
    sa.Column('artifact_paths', app.models.json_type.ConditionalJSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['audio_asset_id'], ['audio_assets.id'], ),
    sa.ForeignKeyConstraint(['processing_job_id'], ['processing_jobs.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.ForeignKeyConstraint(['transcription_id'], ['transcriptions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('processing_job_id')
    )
    op.create_table('transcription_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transcription_id', app.models.json_type.ConditionalUUID(), nullable=False),
    sa.Column('sequence_index', sa.Integer(), nullable=False),
    sa.Column('midi_number', sa.Integer(), nullable=False),
    sa.Column('note_name', sa.String(length=10), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('velocity', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('is_validated', sa.Boolean(), nullable=True),
    sa.Column('validation_action', sa.String(length=20), nullable=True),
    sa.Column('validation_reason', sa.String(length=500), nullable=True),
    sa.Column('hand', sa.String(length=20), nullable=True),
    sa.Column('measure_number', sa.Integer(), nullable=True),
    sa.Column('beat_position', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['transcription_id'], ['transcriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcription_notes_transcription_id'), 'transcription_notes', ['transcription_id'], unique=False)
    op.create_table('difficulty_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('difficulty_variant_id', app.models.json_type.ConditionalUUID(), nullable=False),
    sa.Column('source_note_id', sa.Integer(), nullable=False),
    sa.Column('sequence_index', sa.Integer(), nullable=False),
    sa.Column('midi_number', sa.Integer(), nullable=False),
    sa.Column('note_name', sa.String(length=10), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('velocity', sa.Integer(), nullable=True),
    sa.Column('hand', sa.String(length=20), nullable=True),
    sa.Column('measure_number', sa.Integer(), nullable=True),
    sa.Column('beat_position', sa.Float(), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['difficulty_variant_id'], ['difficulty_variants.id'], ),
    sa.ForeignKeyConstraint(['source_note_id'], ['transcription_notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_difficulty_notes_difficulty_variant_id'), 'difficulty_notes', ['difficulty_variant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_difficulty_notes_difficulty_variant_id'), table_name='difficulty_notes')
    op.drop_table('difficulty_notes')
    op.drop_index(op.f('ix_transcription_notes_transcription_id'), table_name='transcription_notes')
    op.drop_table('transcription_notes')
    op.drop_table('processing_provenances')
    op.drop_table('difficulty_variants')
    op.drop_index(op.f('ix_curriculum_exercises_lesson_id'), table_name='curriculum_exercises')
    op.drop_table('curriculum_exercises')
    op.drop_table('transcriptions')
    op.drop_index(op.f('ix_curriculum_lessons_unit_id'), table_name='curriculum_lessons')
    op.drop_index(op.f('ix_curriculum_lessons_slug'), table_name='curriculum_lessons')
    op.drop_table('curriculum_lessons')
    op.drop_table('processing_jobs')
    op.drop_table('lesson_song')
    op.drop_index(op.f('ix_lesson_progress_user_id'), table_name='lesson_progress')
    op.drop_index(op.f('ix_lesson_progress_lesson_id'), table_name='lesson_progress')
    op.drop_table('lesson_progress')
    op.drop_index(op.f('ix_curriculum_units_slug'), table_name='curriculum_units')
    op.drop_index(op.f('ix_curriculum_units_module_id'), table_name='curriculum_units')
    op.drop_table('curriculum_units')
    op.drop_index(op.f('ix_curriculum_checkpoints_module_id'), table_name='curriculum_checkpoints')
    op.drop_table('curriculum_checkpoints')
    op.drop_index(op.f('ix_student_learning_states_user_id'), table_name='student_learning_states')
    op.drop_table('student_learning_states')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_lessons_teacher_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_slug'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_is_published'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_is_deleted'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_difficulty'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_category'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_friendships_user_id'), table_name='friendships')
    op.drop_index(op.f('ix_friendships_friend_id'), table_name='friendships')
    op.drop_table('friendships')
    op.drop_index(op.f('ix_friend_requests_sender_id'), table_name='friend_requests')
    op.drop_index(op.f('ix_friend_requests_receiver_id'), table_name='friend_requests')
    op.drop_table('friend_requests')
    op.drop_index(op.f('ix_curriculum_modules_slug'), table_name='curriculum_modules')
    op.drop_index(op.f('ix_curriculum_modules_path_id'), table_name='curriculum_modules')
    op.drop_table('curriculum_modules')
    op.drop_table('audio_assets')
    op.drop_table('users')
    op.drop_index(op.f('ix_songs_title'), table_name='songs')
    op.drop_index(op.f('ix_songs_educational_category'), table_name='songs')
    op.drop_index(op.f('ix_songs_difficulty'), table_name='songs')
    op.drop_index(op.f('ix_songs_created_at'), table_name='songs')
    op.drop_table('songs')
    op.drop_index(op.f('ix_learning_paths_slug'), table_name='learning_paths')
    op.drop_table('learning_paths')
    # ### end Alembic commands ###
